"""
Incident report formatter.
Turns the agent's investigation into a structured markdown report.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path


def format_report(
    test_name: str,
    model: str,
    column: str,
    failing_rows: int,
    root_cause: str,
    upstream_trace: list[str],
    investigation_steps: list[str],
    recommended_fix: str,
    severity: str,
    raw_agent_output: str = "",
) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lineage = " → ".join(upstream_trace) if upstream_trace else "unknown"
    steps = "\n".join(f"{i+1}. {s}" for i, s in enumerate(investigation_steps))

    return f"""# Data Quality Incident Report

**Generated:** {ts}
**Severity:** {severity.upper()}

---

## Failing Test
- **Test:** `{test_name}`
- **Model:** `{model}`
- **Column:** `{column}`
- **Failing rows:** {failing_rows:,}

---

## Root Cause
{root_cause}

---

## Upstream Lineage Trace
```
{lineage}
```

---

## Investigation Steps
{steps}

---

## Recommended Fix
{recommended_fix}

---

*Generated by dbt Incident Investigator — agentic root-cause analysis*
"""


def save_report(report_md: str, output_dir: str = "reports") -> Path:
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    path = Path(output_dir) / f"incident_{ts}.md"
    path.write_text(report_md, encoding="utf-8")
    return path
