"""
dbt manifest tools — parse manifest.json for lineage, compiled SQL, and test info.

The manifest.json is generated by `dbt compile` or `dbt build` and contains
the full dependency graph, compiled SQL, and test definitions for every node.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def load_manifest(manifest_path: str) -> dict[str, Any]:
    with open(manifest_path, encoding="utf-8") as f:
        return json.load(f)


def get_model_lineage(manifest: dict, model_name: str) -> dict[str, Any]:
    """Return upstream parents and downstream children for a model."""
    nodes = manifest.get("nodes", {})
    sources = manifest.get("sources", {})

    # Find the node — try model prefix first, then search
    node_key = f"model.{manifest.get('metadata', {}).get('project_id', '')}.{model_name}"
    node = nodes.get(node_key)
    if not node:
        for k, v in nodes.items():
            if v.get("name") == model_name and v.get("resource_type") == "model":
                node = v
                node_key = k
                break

    if not node:
        return {"error": f"Model '{model_name}' not found in manifest."}

    def _label(key: str) -> str:
        parts = key.split(".")
        return parts[-1] if parts else key

    parents = [_label(p) for p in node.get("depends_on", {}).get("nodes", [])]
    children = [
        _label(k) for k, v in nodes.items()
        if node_key in v.get("depends_on", {}).get("nodes", [])
    ]

    return {
        "model": model_name,
        "schema": node.get("schema"),
        "description": node.get("description", ""),
        "parents": parents,
        "children": children,
        "columns": list(node.get("columns", {}).keys()),
        "tags": node.get("tags", []),
        "path": node.get("original_file_path", ""),
    }


def get_model_sql(manifest: dict, model_name: str) -> dict[str, Any]:
    """Return the compiled SQL for a model."""
    nodes = manifest.get("nodes", {})
    for k, v in nodes.items():
        if v.get("name") == model_name and v.get("resource_type") == "model":
            return {
                "model": model_name,
                "compiled_sql": v.get("compiled_code") or v.get("raw_code", ""),
                "path": v.get("original_file_path", ""),
            }
    return {"error": f"Model '{model_name}' not found."}


def get_failing_tests(manifest: dict, run_results_path: str) -> list[dict[str, Any]]:
    """Parse dbt run_results.json and return all failing tests with context."""
    try:
        with open(run_results_path, encoding="utf-8") as f:
            run_results = json.load(f)
    except FileNotFoundError:
        return [{"error": f"run_results.json not found at {run_results_path}"}]

    nodes = manifest.get("nodes", {})
    failures = []
    for result in run_results.get("results", []):
        if result.get("status") not in ("fail", "error"):
            continue
        uid = result.get("unique_id", "")
        node = nodes.get(uid, {})
        attached_node = node.get("attached_node", "")
        model_name = attached_node.split(".")[-1] if attached_node else ""
        failures.append({
            "test_name":    uid.split(".")[-1],
            "unique_id":    uid,
            "model":        model_name,
            "column":       node.get("column_name", ""),
            "test_type":    node.get("test_metadata", {}).get("name", ""),
            "status":       result.get("status"),
            "message":      result.get("message", ""),
            "failures":     result.get("failures", 0),
        })
    return failures


def get_source_info(manifest: dict, source_name: str) -> dict[str, Any]:
    """Return metadata for a raw source table."""
    sources = manifest.get("sources", {})
    for k, v in sources.items():
        if v.get("name") == source_name or v.get("identifier") == source_name:
            return {
                "source": source_name,
                "schema": v.get("schema"),
                "database": v.get("database"),
                "description": v.get("description", ""),
                "loaded_at_field": v.get("loaded_at_field", ""),
                "columns": list(v.get("columns", {}).keys()),
            }
    return {"error": f"Source '{source_name}' not found."}
